### ISSUE TITLE
Access rights to publish package

### ISSUE THREAD

**Issue by christian-bromann** [FloValence/wdio-concise-reporter#3]
Hey,

we are currently looking into porting the reporter to the new v5 framework. In order to be able to publish the package as part of the wdio ecosystem we (I) need access rights to publish this package. Could you grant these? Thanks!

**Comment by FloValence** [comment]
Hello @christian-bromann,
I’m currently travelling, I will give you the rights as soon as I’m able to use a computer. (Probably around the 8th of July)
Is this all you need ?

**Comment by christian-bromann** [comment]
> Is this all you need ?

Yes, that would be awesome. Thanks!

**Comment by christian-bromann** [comment]
ping @FloValence

**Comment by FloValence** [comment]
Hello,
I just added you as Maintainer on NPMJS, as well as Collaborator on GItHub,
Is it Ok for you?

**Comment by christian-bromann** [comment]
Yes, thank you!

**Comment by christian-bromann** [comment]
Added you to the Webdriverio project committers too.

**Comment by FloValence** [comment]
Ok, Thank you!
